#ifndef	SYSP_VERSION_INCLUDED
#define SYSP_VERSION_INCLUDED

#define SYSP_MAKE_STR_HELPER(x) #x
#define SYSP_MAKE_STR(x) SYSP_MAKE_STR_HELPER(x)

#define SYSP_VERSION_MAJOR		1
#define SYSP_VERSION_MINOR		4
#define SYSP_VERSION_PATCH		0
#define SYSP_VERSION_BETA		0
#define SYSP_VERSION_VERSTRING	SYSP_MAKE_STR(SYSP_VERSION_MAJOR) "." SYSP_MAKE_STR(SYSP_VERSION_MINOR) "." SYSP_MAKE_STR(SYSP_VERSION_PATCH) "." SYSP_MAKE_STR(SYSP_VERSION_BETA)

#endif
