#ifndef	SYSTEMPAGE_VERSION_INCLUDED
#define SYSTEMPAGE_VERSION_INCLUDED

#define SYSTEMPAGE_MAKE_STR_HELPER(x) #x
#define SYSTEMPAGE_MAKE_STR(x) SYSTEMPAGE_MAKE_STR_HELPER(x)

#define SYSTEMPAGE_VERSION_MAJOR		1
#define SYSTEMPAGE_VERSION_MINOR		2
#define SYSTEMPAGE_VERSION_PATCH		2
#define SYSTEMPAGE_VERSION_BETA			0
#define SYSTEMPAGE_VERSION_VERSTRING	SYSTEMPAGE_MAKE_STR(SYSTEMPAGE_VERSION_MAJOR) "." SYSTEMPAGE_MAKE_STR(SYSTEMPAGE_VERSION_MINOR) "." SYSTEMPAGE_MAKE_STR(SYSTEMPAGE_VERSION_PATCH) "." SYSTEMPAGE_MAKE_STR(SYSTEMPAGE_VERSION_BETA)

#endif
